KeycloakSettings:
    Authority: http://server.arkhipenko.lan:50000/realms/aid-kit-realm
    MetadataAddress: http://server.arkhipenko.lan:50000/realms/aid-kit-realm/.well-known/openid-configuration
    IsRequireHttpsMetadata: false
    IsValidateIssuer: false
    ValidIssuers:
        - http://server.arkhipenko.lan:50000/realms/aid-kit-realm
    IsValidateAudience: true
    ValidAudiences:
        - medication-control-service-client
    ServiceSettings:
        Service: medication-control-service-client
        Roles:
            - Key: AdminRole
              Value: medication-control-service-admin
            - Key: UserRole
              Value: medication-control-service-user

UserHelper:
  UserService:
    Url: http://server.arkhipenko.lan:60101